"""add_unique_constraint_to_ai_highlights

Revision ID: 0f45440a59e3
Revises: bc93eee003b1
Create Date: 2026-08-27 13:22:41.851281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f45440a59e3'
down_revision: Union[str, Sequence[str], None] = 'bc93eee003b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_highlights_meeting_id'), table_name='ai_highlights')
    op.create_index(op.f('ix_ai_highlights_meeting_id'), 'ai_highlights', ['meeting_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_highlights_meeting_id'), table_name='ai_highlights')
    op.create_index(op.f('ix_ai_highlights_meeting_id'), 'ai_highlights', ['meeting_id'], unique=False)
    # ### end Alembic commands ###
